
       ;4_4 SPACE EXAMPLE        
               
               
;SET VIDEO MODE

MOV AH,00
MOV AL,03 
INT 10H



;DISPLAY
MOV AH,09   ;RESERVED DISPLAY OPTION ?
MOV BH,00   ;PAGE NUMBER
MOV AL,20H  ;ASCII SPACE 
MOV CX,800H ;REPEAT TIME 
MOV BL,1FH  ;HIGH INTENSITY WHITE ON BLUDE
INT 10H