  TITLE PROG 6-1 FIND THE AVERAGE TEMPERATURE
  PAGE 60,132
  .MODEL STMALL
  .STACK 64
  .DATA
  SIGN_DAT DB +13,-10,+19,+14,-18,-9,+12,-19,+16
  AVERAGE DW ?
  REMAINDER DW ?
  .CODE
  MAIN PROC FAR
  MOV AX,@DATA
  MOV DS,AX
  MOV CX,9 
  SUB BX,BX 
  MOV SI,OFFSET SIGN_DAT 
BACK:MOV AL,[SI] 
  CBW 
  ADD BX,AX 
  INC SI 
  LOOP BACK 
  MOV AL,9 
  CBW 
  MOV CX,AX 
  MOV AX,BX 
  CWD 
  IDIV CX 
  MOV AVERAGE,AX 
  MOV REMAINDER,DX 
  MOV AH,4CH
  INT 21H 
  MAIN ENDP
  END MAIN

